### ISSUE TITLE
Rename wrongChoice

### ISSUE THREAD

**Issue by henrikmdev** [B-ANTONY-J/Hangman#1]
https://github.com/B-ANTONY-J/Hangman/blob/f77bd5180f80060c165f6d1660af363845af9ab9/Hangman/Program.cs#L13

I recommend you rename wrongChoice to wrongGuess or numberOfWrongGuesses or something like that because it's not intuitive what is meant by "choice".

**Comment by B-ANTONY-J** [comment]
I've changed the variable to "incorrectGuess" because the variable "wrongGuess" I already have assigned as an incrementor for my while loop.
