### ISSUE TITLE
Misleading prompt

### ISSUE THREAD

**Issue by henrikmdev** [B-ANTONY-J/Hangman#3]
https://github.com/B-ANTONY-J/Hangman/blob/f77bd5180f80060c165f6d1660af363845af9ab9/Hangman/Program.cs#L305

I recommend that you change the prompt at the end because it sounds like the user can press any key to continue playing again, but then the program just exits haha

**Comment by B-ANTONY-J** [comment]
This was replaced with Console.WriteLine("\nThank Your for Playing!\nPress any key to exit...\n");
