### ISSUE TITLE
Two correctGuess data types

### ISSUE THREAD

**Issue by henrikmdev** [B-ANTONY-J/Hangman#6]
https://github.com/B-ANTONY-J/Hangman/blob/f77bd5180f80060c165f6d1660af363845af9ab9/Hangman/Program.cs#L104
https://github.com/B-ANTONY-J/Hangman/blob/f77bd5180f80060c165f6d1660af363845af9ab9/Hangman/Program.cs#L232

I recommend you rename one of these variables because they have the same name but correspond to different data.

**Comment by B-ANTONY-J** [comment]
Changed int correctGuess to int correctGuessInt to clean code code confusion issues.

**Comment by mayisa87** [comment]
I would recommend not to name an variable by its datatype. So instead of calling the correctGuess which is of type int correctGuessInt, you could leave it as correctGuess and rename the list to "guessedLetters".

**Comment by B-ANTONY-J** [comment]
int "correctGuessInt" changed back to "correctGuess" and char list changed from "correctGuess" to "guessedLetters"
